version: "3"
services:
  app:
    container_name: inali-backend
    restart: always
    build: ./
    ports:
      - "3000:3000"
#    volumes:
#      - .:/app
#    links:
#      - mongo
#volumes:
#  data-volume:
